In [ ]:
# Name: Rupsa Karak  PRN: 25070123098
# Experiment 13
# Aim: To perform preprocessing on a dataset and Dealnig with Missing Values

In [1]:
import pandas as pd
import numpy as np
df1= pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
print(df1)

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
df1.isna() #Boolean function for finding null, if null gives true otherwise false

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna()  #Boolean function for finding not null, if not null gives true otherwise false

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
df1.isna().sum()  #columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.isna().sum(axis=1) #rowise na values

0    0
1    1
2    2
dtype: int64

In [ ]:
df1.dropna()  #Nan Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1.dropna(axis=1) #Nan Columns are dropped

   C3
0  10
1  20
2  30

In [ ]:
df1.fillna(value='DEFAULT') #replacing nan values

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
df1.fillna(0) #replacing with zero

     C1    C2  C3
0  11.0  15.0  10
1  21.0   0.0  20
2   0.0   0.0  30

In [ ]:
df1.fillna(df1.mean())  #Mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [4]:
df1.apply(lambda row : row.fillna(row.mean()), axis=1) #Mean values rowise are calculated

     C1    C2    C3
0  11.0  15.0  10.0
1  21.0  20.5  20.0
2  30.0  30.0  30.0

In [8]:
# Preprocessing on Dataset-1
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
df

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [10]:
# Step 1: Replacing null values with nan
df.replace("-", np.nan, inplace=True)
display(df)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [17]:
# Step 2: Replace '-' with Nan to mark missing values
#df.reaplce("-", np.nan, inplace=True)
#Convert columns to mueric where nedded
df["Age"] = pd.to_numeric(df["Age"],errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"],errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        CSE     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [18]:
# Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Marks"].fillna(df["Marks"].median(), inplace=True)
display(df)

/tmp/ipykernel_9190/3098735472.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/tmp/ipykernel_9190/3098735472.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [11]:
# Step 5: Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()
display(df)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        CSE     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [19]:
# Step 6: Convert Admission_Date to standard datetime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], format = 'mixed',dayfirst=True)
display(df)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-06-01
1      102  Rohan  20.75   90.0         IT     2023-06-03
2      103  Meera  21.00   86.5        CSE     2023-06-05
3      104  Karan  20.00   88.0        CSE     2023-06-07
4      105   Anil  22.00   76.0       E&TC     2023-06-10